#! /usr/bin/env python3

import numpy as np
from math import *
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import sys, os

fontSize = 18
MIN_PLOT_MAGNITUDE = 6.5

def readFEGlobal(fname='FE_Global.txt'):
    icstart, icend, C_mesh = 1, 1, 2
    with open(fname, 'r') as f:
        lines = [l for l in f if l.strip() and not l.strip().startswith('#')]
    C_mesh = int(lines[0].split('#')[0])
    for line in lines:
        if 'icstart' in line:
            vals = line.split('#')[0].split()
            icstart, icend = int(vals[0]), int(vals[1])
            break
    return icstart, icend, C_mesh

def plotRuptureDynamicsForOneEq(eqId, icstart, nsmp, points, nsmpnv,
                                 numOfFts, numOfFtNodes, maxNumOfFtNodes, ftNodeIndexArr,
                                 allRes, totftnode, pts_scale=1.0e-3, length_scale=1.0):
    plotPath = './aPlots/'
    if not os.path.exists(plotPath):
        os.mkdir(plotPath)
    outputFname = plotPath + 'cRuptureDynamics' + str(eqId) + '.png'

    # each cycle is totftnode rows stacked in allRes; eqId is 1-based, icstart-based
    cycIdx = eqId - icstart
    res = allRes[cycIdx * totftnode : (cycIdx + 1) * totftnode, :]

    moment = 0.
    seismoDepth = 22.e3
    rou = 2670.0
    vs  = 3464.0
    rigidity = rou * vs * vs

    fig, ax = plt.subplots(4, 1, figsize=(10, 15))

    for iFt in range(numOfFts):
        slaveRows  = np.arange(iFt * maxNumOfFtNodes + 1,
                               iFt * maxNumOfFtNodes + numOfFtNodes[iFt] - 1)
        resRows    = np.arange(ftNodeIndexArr[iFt] + 1, ftNodeIndexArr[iFt + 1] - 1)
        xcoord     = points[nsmp[slaveRows, 0], 0] * pts_scale   # km

        ax[0].plot(xcoord, res[resRows, 0] / 1e6, linewidth=2)
        ax[0].set_ylabel('Shear stress (MPa)', fontsize=fontSize)
        ax[0].tick_params(axis='both', which='major', labelsize=fontSize)

        ax[1].plot(xcoord, res[resRows, 1] / 1e6, linewidth=2)
        ax[1].set_ylabel('Normal stress (MPa)', fontsize=fontSize)
        ax[1].tick_params(axis='both', which='major', labelsize=fontSize)

        ax[2].plot(xcoord, res[resRows, 2], linewidth=2)
        ax[2].set_ylabel('Slip (m)', fontsize=fontSize)
        ax[2].tick_params(axis='both', which='major', labelsize=fontSize)
        for i in resRows:
            # C_mesh=3 stores node-associated fault length in km; convert here so
            # seismic moment is always computed in SI units.
            moment += (
                res[i, 2]
                * nsmpnv[iFt * maxNumOfFtNodes + (i - ftNodeIndexArr[iFt]), 2]
                * length_scale
                * seismoDepth
                * rigidity
            )

        ax[3].plot(xcoord, res[resRows, 4], linewidth=2)
        ax[3].set_ylabel('Rupture time (s)', fontsize=fontSize)
        ax[3].set_ylim(0, 50)
        ax[3].set_xlabel('Along strike distance (km)', fontsize=fontSize)
        ax[3].tick_params(axis='both', which='major', labelsize=fontSize)

    if moment > 0:
        magnitude = 2. / 3. * log10(moment * 1.e7) - 10.7
    else:
        magnitude = 0.
    ax[0].set_title('EQ ID ' + str(eqId) + '; Magnitude ' + "{:.2f}".format(magnitude), fontsize=fontSize)
    print('EQ ID', eqId, '; Magnitude', "{:.2f}".format(magnitude),
          '; Moment', "{:.2e}".format(moment), 'N-m')

    if magnitude > MIN_PLOT_MAGNITUDE:
        plt.savefig(outputFname, dpi=300)
    plt.close()

def plotRuptureDynamics():
    icstart, icend, C_mesh = readFEGlobal('FE_Global.txt')

    if len(sys.argv) == 1:
        mode = 1
    elif len(sys.argv) == 2:
        eqId = int(sys.argv[1])
        mode = 2
    else:
        print('Error: provide a single cycle ID or no arguments.')
        sys.exit()

    if C_mesh == 2:
        # C_mesh=2: nsmp.txt is 1-indexed; vert.txt in meters; old file names
        nsmp   = np.loadtxt('nsmp.txt', dtype=int) - 1   # convert to 0-based
        points = np.loadtxt('vert.txt')                   # meters
        nsmpnv = np.loadtxt('nsmpnv.txt')
        mesh_info_file = 'meshGeneralInfo.txt'
        pts_scale = 1.0e-3   # m -> km for x-axis
        length_scale = 1.0   # nsmpnv length already in m
    else:
        # C_mesh=3: nsmp.txt is 0-indexed; vert.txt in km; new file names
        nsmp   = np.loadtxt('nsmp.txt', dtype=int)        # already 0-based
        points = np.loadtxt('vert.txt')                   # km
        nsmpnv = np.loadtxt('nsmpTanLen.txt')
        mesh_info_file = 'meshGeneralInfo.txt'
        pts_scale = 1.0                                   # already km
        length_scale = 1.0e3                              # km -> m for moment

    with open(mesh_info_file, 'r') as f:
        next(f)
        numOfFtNodes = list(map(int, f.readline().split()))
    print('nfnode:', numOfFtNodes)

    numOfFts        = len(numOfFtNodes)
    maxNumOfFtNodes = max(numOfFtNodes)
    totftnode       = sum(numOfFtNodes)
    ftNodeIndexArr  = np.zeros(numOfFts + 1, dtype=int)
    for iFt in range(numOfFts):
        ftNodeIndexArr[iFt + 1] = np.sum(numOfFtNodes[:iFt + 1])

    # all cycles are stacked in one file: totalop.txt{icstart}
    fname   = 'totalop.txt' + str(icstart)
    allRes  = np.loadtxt(fname)
    ncycles = allRes.shape[0] // totftnode
    print('Cycles available:', ncycles)

    if mode == 1:
        for ic in range(icstart, icstart + ncycles):
            plotRuptureDynamicsForOneEq(ic, icstart, nsmp, points, nsmpnv,
                                        numOfFts, numOfFtNodes, maxNumOfFtNodes,
                                        ftNodeIndexArr, allRes, totftnode, pts_scale, length_scale)
    elif mode == 2:
        plotRuptureDynamicsForOneEq(eqId, icstart, nsmp, points, nsmpnv,
                                    numOfFts, numOfFtNodes, maxNumOfFtNodes,
                                    ftNodeIndexArr, allRes, totftnode, pts_scale, length_scale)

def _main_func(description):
    plotRuptureDynamics()

if __name__ == "__main__":
    _main_func(__doc__)
