% This script is used to visulize meshes generated by EQdyna2d_2.0.0.
% 09082020, DL.
% Input: vert.txt, fac.txt
%  x1.txt, x2.txt, x3.txt ... (or other names for files storing fault geometry contolling points)
clear all; close all;

path_mesh = './XX/' %please define the path to mesh files: vert.txt, etc. 
path_cp = './XX/' %please define the path to controlling points files: x1.txt, etc. 

load(strcat(path_mesh,'vert.txt'));
load(strcat(path_mesh,'fac.txt'));
patch('Vertices',vert,'Faces',fac,'Facecolor','w')
axis off
axis equal
hold on

x1 = load(strcat(path_cp,'/x1_1.txt'));
x1 = load(strcat(path_cp,'/x2_1.txt'));
x1 = load(strcat(path_cp,'/x3_1.txt'));

x1 = x1 * 1000; % to meters.
x2 = x2 * 1000;
x3 = x3 * 1000;

plot(x1(:,1),x1(:,2),'m');
plot(x2(:,1),x2(:,2),'c');
plot(x3(:,1),x3(:,2),'r');

set(gcf,'renderer','zbuffer');
%print -djpeg -r600 mesh
